
index:
  number_of_shards: 1
  number_of_replicas: 0

path:
  data: runtime/elasticsearch/data
  work: runtime/elasticsearch/work
  logs: runtime/elasticsearch/logs
  conf: .

gateway:
  recover_after_nodes: 1
  expected_nodes: 1

# bind only to localhost, so we aren't visible and we don't multicast discover others
network.host: localhost

# could instead/also disable multicast discovery or even unicast discovery;
# not necessary for localhost config but may be useful for cross-server deployment
#discovery.zen.ping.multicast.enabled: false
#discovery.zen.ping.unicast.enabled: false
#discovery.zen.ping.unicast.hosts: localhost

